version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fast
      POSTGRES_DB: bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
